services:
  docs:
    networks: [a-fmhy]
    build:
      context: .
      dockerfile: Dockerfile
    image: a-fmhy-docs
    container_name: docs
    restart: unless-stopped
    ports:
      - '4173:80'

networks:
  a-fmhy:
